import type { NextPage } from 'next';
import React from 'react';
import Head from 'next/head';
import styles from '../../../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Word App</title>
        <meta name='description' content='Generated by practicing English' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>hello</main>
    </div>
  );
};

export default Home;
