import type { NextPage } from 'next';
import React from 'react';
import Head from 'next/head';
import styles from '../../../styles/Home.module.scss';
import Header from '../../components/Header';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | RED GYM PROJECT</title>
        <meta name='description' content='Generated by practicing English' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className='text-3xl font-bold text-red-500 uppercase'>
          Red gym project
        </h1>
      </main>
    </div>
  );
};

export default Home;
